### ISSUE TITLE
Populate units and quantity-kinds from QUDT

### ISSUE THREAD

**Issue by roblinksdata** [GSS-Cogs/reusable-rdf-resources#2]
Write a python script to populate the [units.json](https://github.com/GSS-Cogs/reusable-rdf-resources/blob/main/units.json) and [quantity-kinds.json](https://github.com/GSS-Cogs/reusable-rdf-resources/blob/main/quantity-kinds.json) JSON $schema enums with the available units + quantity-kinds specified in the QUDT [units catalogue](http://www.qudt.org/doc/DOC_VOCAB-UNITS.html) & [quantity kinds catalogue](http://www.qudt.org/doc/DOC_VOCAB-QUANTITY-KINDS.html).

**N.B. This script should be repeatable and not overwrite or remove any non-QUDT units/quantity-linds from the $schema enums.**

Also, make sure you're using the RDF source for this data instead of scraping or anything like that.

Make sure to keep the script in a new folder called `scripts` (you'll need to create a new poetry environment inside here so you can install all the dependencies you need like rdflib).

N.B. You don't need to set up any automation to run this periodically just yet, we'll run it manually for now.

**Comment by mikeAdamss** [comment]
TODO:

- [x] Create `/scripts` dir with poetry files. We'll need `requests` (probably) and `rdflib`, possibly more.
- [x] Define a list of RDF resources in the form of urls, starting with units catalogue & quantity kinds catalogue as listed for this task.
- Create script that:
     - [x] Iterates through the above and for each
     - [x] Gets the RDF resource.
     - [x] Reads the RDF resources into `rdflib`
     - [x] Uses `rdflib` to get the identifying url for each thing, i.e `www.url-in-question/something#i-am-a-unit`
     - [x] Read the appropriate .json file in from this repos base directory and (if the url in question is not already there!) add it to the list in the `enum` field before writing the json file back.

Notes:

Iterating a list of source urls may or may not be appropriate. If its cleaner to do them as separate functions that's fine.

Include a `REAME.md` in the `./scripts` directory explaining what it's doing and how to use it.

Try and write in a DRY way. We'll likely be expanding on sources in time, so organise with that in mind. EG: have a "get data" function, a "convert to rdf" function, some SPARQL queries as constants and an "update json" function. Making use of any given future source should just be a case of composing these things together (and perhaps adding a new SPARQL query variant where needed).
