### ISSUE TITLE
Create CSV-W for Analyst Function `obStatus` Concept Scheme

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/reusable-rdf-resources#23]
There are two distinct concept schemes to this ticket for creating the marker columns we want to support in the new form of sdmx:obsStatus concept schemes. We need this to produce the high quality statistical data representation in the Explore Subnational Statistics project.

This ticket should be done in concert with #15.

Create a CSV-W which will allow the use of the Analyst Function list of Marker Characters from their Using symbols and shorthand to create an observation status column.

Follow the example CSV-W json and first line of the csv to complete the concept scheme. Then use the code list generated from the inputs of #15 to provide the additional details expected in a well described concept scheme. Use the new csvcubed code list command launched in version 0.3.0 to generate the CSV-W. This will give you two json files to one CSV.

Once you've got the AF concept scheme completed, go back to the SDMX one, and clean up the code lists by following the "cleaner" manual CSV-W we have created in this one.

**Comment by roblinksdata** [comment]
Hasn't this been done now?
