### ISSUE TITLE
Expand licenses to include all creative commons licenses.

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/reusable-rdf-resources#6]
Write the turtle and update https://github.com/GSS-Cogs/GDP-vocabs/blob/master/vocabs/licenses.ttl.

- [x] Get the change on staging
- [x] Ensure the licenses.ttl contains definitions for our existing licenses in [the licenses.json schema file](https://github.com/GSS-Cogs/reusable-rdf-resources/blob/main/licenses.json).
- [ ] Once we're satisfied that the licenses have been correctly updated on staging, go to @rossbowen for review & publication

edit:

- [ ] Update sure the licenses documentation page reflects the current state.

**Comment by roblinksdata** [comment]
As part of this task can you create an `all rights reserved` license with some sensible URI for people who don't want to go down the open-data route.
