### ISSUE TITLE
Create publisher for wikipedia/media, etc.

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/reusable-rdf-resources#7]
- [ ] Using the [organisations.csv](https://github.com/GSS-Cogs/reusable-rdf-resources/blob/main/rdf-definitions/organisations/organisations.csv) file added by @mikeAdamss - add wikipedia/media gets added to this list.
- [ ] Ensure you update the [organisations.json](https://github.com/GSS-Cogs/reusable-rdf-resources/blob/main/organisations.json) using the appropriate python script in the `scripts` directory so that JSON auto-complete works for external users.
edit:

- [ ] Ensure that the organisations documentation page (in csvcubed) reflects the current state.

**Comment by mikeAdamss** [comment]
@canwaf - was gonna pick this up but I need a few more details when you get a minute. I'm not sure what we mean by `wikipedia/media, etc`.

do you have any urls or sources I can look at to get the information for any new entries for the csv file please?
